### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 20000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "befdcda0390947c88da669235a5fdce2",
  "accountNumber": "1000000002",
  "amount": 20000
}

### query transaction
GET http://localhost:8080/transaction/58a26c88f6894c9ab62153df353ec787